### PR TITLE
Allow numbers, strings, and integers for overlays

### PR DESCRIPTION
**Pull request by asizemore**
With plot.data [PR #124](https://github.com/VEuPathDB/plot.data/pull/124), addresses backend needs for allowing a gradient colormap.

Specifically, this PR allows all numbers, integers, and strings to be overlay variables
**Important** my logic isn't perfect yet! We can't just allow _all_ strings and numbers. We have to allow all numbers, then also strings with < 9 values. Not sure how to do this yet. Keeping as draft until we figure it out!

### CODE REVIEW

**Review by d-callan — APPROVED** [review]
seems fine, though it makes me wonder if the descriptions should belong outside the individual patterns somehow rather than be repeated across them. something we can worry about later if it becomes a problem i suppose

**Comment by chowington** [comment]
@d-callan Let me know when the changes are deployed on the backend---I don't know what the process is for this repo

**Comment by dmfalke** [comment]
@chowington this should be available on a dev site (dfalke-b). Let me know if you run into issues with that.

**Comment by d-callan** [comment]
this isnt intended for b60 right? so we may have to revert that merge...

**Pull request merged**
